// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PropIntelligence.Infrastructure.Persistence;

#nullable disable

namespace PropIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PropIntelligenceContext))]
    partial class PropIntelligenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropIntelligence.Domain.Entities.Property", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("UnitNumber").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("StreetNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("StreetName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("StreetType").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("FullAddress").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Suburb").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("State").HasColumnType("int");
                b.Property<string>("Postcode").IsRequired().HasMaxLength(4).HasColumnType("nvarchar(4)");
                b.Property<double>("Latitude").HasColumnType("float");
                b.Property<double>("Longitude").HasColumnType("float");
                b.Property<int>("PropertyType").HasColumnType("int");
                b.Property<int>("Bedrooms").HasColumnType("int");
                b.Property<int>("Bathrooms").HasColumnType("int");
                b.Property<int>("CarSpaces").HasColumnType("int");
                b.Property<decimal?>("LandAreaSqm").HasColumnType("decimal(10,2)");
                b.Property<decimal?>("FloorAreaSqm").HasColumnType("decimal(10,2)");
                b.Property<string>("LotNumber").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("PlanNumber").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Suburb");
                b.HasIndex("State");
                b.HasIndex("Postcode");
                b.HasIndex("Suburb", "State");
                b.HasIndex("Latitude", "Longitude");
                b.ToTable("Properties");
            });

            modelBuilder.Entity("PropIntelligence.Domain.Entities.SalesHistory", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("PropertyId").HasColumnType("uniqueidentifier");
                b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
                b.Property<DateTime>("SaleDate").HasColumnType("datetime2");
                b.Property<int>("SaleMethod").HasColumnType("int");
                b.Property<string>("AgencyName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("AgentName").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<int?>("DaysOnMarket").HasColumnType("int");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("PropertyId");
                b.HasIndex("SaleDate");
                b.ToTable("SalesHistory");
            });

            modelBuilder.Entity("PropIntelligence.Domain.Entities.PropertyListing", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("PropertyId").HasColumnType("uniqueidentifier");
                b.Property<int>("ListingType").HasColumnType("int");
                b.Property<decimal?>("AdvertisedPrice").HasColumnType("decimal(18,2)");
                b.Property<string>("PriceText").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("AgencyName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("AgentName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("ListedAt").HasColumnType("datetime2");
                b.Property<DateTime?>("SoldAt").HasColumnType("datetime2");
                b.Property<int?>("DaysOnMarket").HasColumnType("int");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("PropertyId");
                b.HasIndex("Status");
                b.ToTable("PropertyListings");
            });

            modelBuilder.Entity("PropIntelligence.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("Role").HasColumnType("int");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime?>("LastLogin").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("PropIntelligence.Domain.Entities.SalesHistory", b =>
            {
                b.HasOne("PropIntelligence.Domain.Entities.Property", "Property")
                    .WithMany("SalesHistoryRecords")
                    .HasForeignKey("PropertyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Property");
            });

            modelBuilder.Entity("PropIntelligence.Domain.Entities.PropertyListing", b =>
            {
                b.HasOne("PropIntelligence.Domain.Entities.Property", "Property")
                    .WithMany("Listings")
                    .HasForeignKey("PropertyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Property");
            });

            modelBuilder.Entity("PropIntelligence.Domain.Entities.Property", b =>
            {
                b.Navigation("SalesHistoryRecords");
                b.Navigation("Listings");
            });
#pragma warning restore 612, 618
        }
    }
}
